### ISSUE TITLE
[Debug mode] Necessario reboot device se viene attivato il "Ripristino SDK" 

### ISSUE THREAD

**Issue by mdecandia81** [noiapp/noi-app-android#20]
Versione app 0.3.0 Debug.

Se viene attivato il "Ripristina SDK" nella view di Debug, la sincronizzazione non riparte se non facendo un reboot del device.

**Comment by mauriziopapini** [comment]
Ho fatto un'analisi per questo problema dipende dal fatto che il resetSDK rimuove la nostra "forzatura" per li backend e prova a risolverlo passando per il servizio di discovery che, per adesso, non conosce il nostro backend. Ho fatto una PR per aggiungere il nostro backend (https://github.com/DP-3T/dp3t-discovery/pull/1)
