### ISSUE TITLE
Versione 1.0 visualizzata in dettaglio app

### ISSUE THREAD

**Issue by capoloja** [noiapp/noi-app-android#35]
Su Android 9.0. il dettaglio app riporta la **versione 1.0** invece della 0.3.0

![image](https://user-images.githubusercontent.com/18376610/80912462-5530bb80-8d3d-11ea-94d2-57356ece433c.png)

**Comment by mauriziopapini** [comment]
Proposta da votare: Proporrei di estrarre la versione dal git. Per far questo esiste un plugin per farlo, ho trovato questo https://github.com/gladed/gradle-android-git-version.
Se qualcuno ha idee migliorativi e hints si faccia avanti

**Comment by mauriziopapini** [comment]
Ciao @Magicianred ho incluso un plugin per l'estrazione della versione da git usando git describe tramite l'utilizzo del plugin che ho citato precedentemente.
Per avere una versione corretta è *necessario* usare i tag (la versione 0.3.0 non ha il tag)

**Comment by Magicianred** [comment]
Daccordo con te @mauriziopapini , l'importante si capisca, che ci sia dei riferimenti agli avanzamenti e non lasci confusione sul fatto che si stia testando la versione giusta

+1
