### ISSUE TITLE
Image wizard onboarding too big 

### ISSUE THREAD

**Issue by BruceGitHub** [noiapp/noi-app-android#43]
Nel Nokia 
https://www.nokia.com/phones/en_int/nokia-2-1
Il wizard iniziale al quarto step ha una immagine troppo grande che produce un effetto sgradevole 
come mostrato dall'immagine 

#english
On Nokia model: 
https://www.nokia.com/phones/en_int/nokia-2-1
The initial wizard on four step it has an image too big that produce an  ugly effect. 

<img width="200" alt="wizard" src="https://user-images.githubusercontent.com/5399875/81015131-69b8a500-8e5e-11ea-9648-61e7d53aab27.jpeg">

Inoltre se non abiliti le autorizzazioni, ma fai scroll al centro schermo il wizard va avanti. Visto che invece il bottone è grigio lo scroll non dovrebbe essere permesso

#english
Further, if you do not allow authorization, and go forward with a swipe, is send you to the next page even if you shouldn't be able to.

<img width="200" alt="wizard" src="https://user-images.githubusercontent.com/5399875/81015504-1c890300-8e5f-11ea-94b7-77c1705fec5a.jpeg">

**Comment by Magicianred** [comment]
Stesso problema della #7

**Comment by BruceGitHub** [comment]
Ci sto guardando appena trovo la soluzione pusho

**Comment by SuperCaliMan** [comment]
I push changes, image is smaller and view autoscrool at the end
