### ISSUE TITLE
Aggiornamento SDK a 0.2.4

### ISSUE THREAD

**Issue by samuele794** [noiapp/noi-app-android#47]
È stata rilasciata la 0.2.4 dell'SDK

Punti critici dell'aggiornamento:
- org.dpppt.android.sdk.backend.models.ApplicationInfo :
aggiunto nuovo parametro `bucketBaseUrl`
- TracingStatus.getNumberOfHandshakes() :
probabilmente rinominato
- TracingStatus.isReportedAsExposed()
probabilmente rinominato
- TracingStatus.wasContactExposed()
probabilmente rinominato
- DP3T.sendIWasExposed()
probabilmente rinominato
- ExposeeAuthData - CallbackListener - ResponseException:
N/D
- TracingStatus.getErrors():
cambiata firma

**Comment by mauriziopapini** [comment]
Ciao @samuele794 esiste già un primo refactor (vedi la issue  #40 aperta da @Magicianred ) che permette il bump alla 0.1.16 (guarda la PR https://github.com/DP-3T/dp3t-app-android/pull/46)  che contiene il 99.9% delle modifiche necessarie (alla 0.2.1 era il 100%). Il problema che vedo riguarda la gestione delle chiavi che dovrà essere concordato BE/FE.

**Comment by Magicianred** [comment]
Può essere un'idea se @samuele794 riporta il testo come commento nella #40 (così teniamo traccia di informazioni utili) e chiudiamo questa come duplicato? Che ne pensi @samuele794 ?

**Comment by mauriziopapini** [comment]
@Magicianred @samuele794 sul repo di dp3t è stata integrata PR per https://github.com/DP-3T/dp3t-app-android/pull/50, questa risolve sia questa issue che quella relativa alla PR DP-3T#46 (https://github.com/DP-3T/dp3t-app-android/pull/46). A mio avviso, come anche detto da @samuele794 e @sciabarracom è necessario allinearci e quindi capire come vogliamo gestire le chiavi BE/FE (per il certificate pinning).
