### ISSUE TITLE
Pulsante abilitazione Bluetooth tagliato su certi device

### ISSUE THREAD

**Issue by henviale** [noiapp/noi-app-android#7]
Durante la fase di onboarding, il pulsante per l'abilitazione del Bluetooth non è visibile su alcuni device (o risulta tagliato su altri), e mancando la barra di scorrimento l'utente non si accorge che questa abilitazione manca.
(https://user-images.githubusercontent.com/16650735/80278867-03af7d80-86fa-11ea-8a91-d809fdef0e8c.jpg)

**Comment by Magicianred** [comment]
Assegned to @BruceGitHub
